### PR TITLE
Minor tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
Let me know if you need me to change something :)

### CODE REVIEW

**Comment by kangax** [comment]
Looks good (As always :)) thanks!

**Comment by XhmikosR** [comment]
Added a couple more changes.

**Comment by XhmikosR** [comment]
For reference  http://gtmetrix.com/compare/PRv1BDHl/tSMQ3CtU

Not bad; imagine concatenating the assets :)

**Comment by kangax** [comment]
Oh yeah.. As expected. Thanks for this! Should be more usable for sure.

**Pull request merged**
