### PR TITLE
Update assets

### PR DESCRIPTION
**Pull request by XhmikosR**
@kangax: I verified with a couple of test files and I didn't notice any issues, but since it's a minor version bump for JSHint you might want to confirm yourself too.

### CODE REVIEW

**Comment by kangax** [comment]
It's probably better to switch to ESLint at some point. Less buggy, more flexible, better maintained.

**Comment by XhmikosR** [comment]
Yeah, I totally agree. But because it's so powerful, I'm not sure how easy the transition will be :)

**Comment by kangax** [comment]
I wonder how many people are actually proactively using JSCritic though... I think it's more of an experiment that hasn't gained much traction. Maybe it'd be better off as a browser extension or a bookmark — something that could be run easily on github repo, for example. I'm sure no one wants to open jscritic.com and paste code in there. Or maybe it's just that no one really cares about these things :)

**Comment by XhmikosR** [comment]
So, @kangax, how about just merging this since it seems to work fine?

**Pull request merged**
